<?php if (isset($this->emissions)) { ?>
	<table width="100%" border="1">
	<?php $emisssion = reset($this->emissions); ?>
	<tr>
	<?php foreach ($emisssion as $key => $field) { ?>
		<th><?php echo $key ?></th>
	<?php }	?>
	</tr>
	<?php foreach ($this->emissions as $emisssion) { ?>
		<tr>
		<?php foreach ($emisssion as $field) { ?>
			<td><?php echo $field ?></td>
		<?php }	?>
		</tr>
	<?php } ?>
	</table>
<?php } ?>