<?php
echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <?php echo $this->headTitle('My ZF site'); ?>
  <?php echo $this->headTitle() ?>
  <?php $this->headLink()->appendStylesheet('/css/global.css'); ?>
  <?php print $this->headLink(); ?>
  <?php print $this->headTitle(); ?>
</head>
<body>
<div id="header" style="background-color: #EEEEEE;">
    <div>
        <b>ZF Quickstart Application</b>
    </div>
    <br />
<?php echo $this->navigation()->breadcrumbs($this->menu)->setMinDepth(0)->setLinkLast(false); ?>
<br>
<?php echo $this->navigation()->menu($this->menu)->setUlClass('nav'); ?>
<?php echo $this->navigation()->links(); ?>
</div>
<br />
<br />
<div id="container">
<?php echo $this->layout()->content ?>
</div>
</body>
</html>