<?php
// application/layouts/scripts/layout.phtml

echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>
<div id="header" style="background-color: #EEEEEE;>
    <div id="header-logo" style="float: left">
        <b>ZF Quickstart Application</b>
    </div>
    <div id="header-navigation">
    	<ul>
    		<li>
    			<a href="/index">MAIN</a>
    		</li>
    		<li>
    			<a href="/client">client</a>
    			<ul>
    				<li><a href="/client/index">index</a></li>
    				<li><a href="/client/briefcase">briefcase</a></li>
    				<li><a href="/client/flows">flows</a></li>
    				<li><a href="/client/inout">inout</a></li>
    				<li><a href="/client/limits">limits</a></li>
    				<li><a href="/client/modelling">modelling</a></li>
    				<li><a href="/client/reports">reports</a></li>
    			</ul>
    		</li>
    		<li>
    			<a href="/emission">emission</a>
    			<ul>
    				<li><a href="/emission/index">index</a></li>
    				<li><a href="/emission/search">search</a></li>
    			</ul>
    		</li>
    		<li>
    			<a href="/ticket">ticket</a>
    			<ul>
    				<li>buy-sell</li>
    				<li>sell-buy</li>
    				<li><a href="/ticket/buy">buy</a></li>
    				<li><a href="/ticket/sell">sell</a></li>
    				<li><a href="/ticket/index">index</a></li>
    			</ul>
    		</li>
    	</ul>
    </div>
</div>

<?php echo $this->layout()->content ?>

</body>
</html>